### ISSUE TITLE
Challenge 2 - node module import errors

### ISSUE THREAD

**Issue by diegoalzate** [scaffold-eth/scaffold-eth-challenges#103]
## Problem
The vscode settings file is pointing to the wrong directory for the solidity node modules, right now it is `   "solidity.packageDefaultDependenciesDirectory": "packages/hardhat-ts/node_modules"`. The problem here is that the `hardhat-ts` folder does not exist.

## Possible Solution
change `"solidity.packageDefaultDependenciesDirectory": "packages/hardhat-ts/node_modules"` to `"solidity.packageDefaultDependenciesDirectory": "packages/hardhat/node_modules"`

**Comment by Quanhua-Guan** [comment]
https://github.com/scaffold-eth/scaffold-eth-challenges/pull/136 take a look
