### ISSUE TITLE
Challenge 3 - Dice Game - Roll animation/buttons gets stuck

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/scaffold-eth-challenges#110]
Occasionally the roll animation will get stuck in the rolling state, and the roll button will stay disabled until page reload.

**Comment by pankaj512** [comment]
It is fixed? If not could you please provide details about it like browser, js or ts?

**Comment by 2283216063** [comment]
To the moon

**Comment by ZakGriffith** [comment]
In testing today, this doesn't appear to be an issue any longer.
