### ISSUE TITLE
Build challenge-7 (Create A Stream)

### ISSUE THREAD

**Issue by codenamejason** [scaffold-eth/scaffold-eth-challenges#12]
Challenge-7-create-stream needs built out.

**Comment by brendanboyle87** [comment]
Do we think a part of this challenge will be building a custom UI or do we want to have it mostly there matching the buidlGuidl pages - http://bboyle.buidlguidl.com/ ?

**Comment by codenamejason** [comment]
> Do we think a part of this challenge will be building a custom UI or do we want to have it mostly there matching the buidlGuidl pages - http://bboyle.buidlguidl.com/ ?

Haven't even thought that far yet. Not sure how to curate this one yet, open to ideas @brendanboyle87
