### ISSUE TITLE
Challenge 0: Getting Error on Yarn Deploy

### ISSUE THREAD

**Issue by abdul-maajid** [scaffold-eth/scaffold-eth-challenges#139]
I am getting this error when I run **yarn deploy**. I tried different solutions but not working.
does anyone also having this issue?

`TypeError: ethers.getContract is not a function`

![image](https://user-images.githubusercontent.com/53260291/182088039-4ec95c6e-e19a-4005-83fa-7baf6865b96a.png)

**Comment by pankaj512** [comment]
Hi, Did you ran yarn install? It seems like your ethers package is old or not installed. And if you figured out this issue then please close this issue. 

Thanks

**Comment by abdul-maajid** [comment]
Solved this.
