### ISSUE TITLE
I'm running into a problem that I can't solve at the moment and I'd love to be able to get help. thanks for your help.

### ISSUE THREAD

**Issue by banjacke** [scaffold-eth/scaffold-eth-challenges#170]
I'm a newbie and I hope to learn more, thanks for your answers.
![未命名1660821199](https://user-images.githubusercontent.com/111337509/185382009-099c71ef-25f0-4012-8fa9-fd617e1d96c6.png)

**Comment by codenamejason** [comment]
What step are you on @banjacke

**Comment by ZakGriffith** [comment]
This question is best asked in the specific challenge Telegram channel.  You can find a link to the channel's telegram in the readme file.
