### ISSUE TITLE
Challenge 0: Open Sea Side Quest Import Instructions

### ISSUE THREAD

**Issue by elijahsullivan** [scaffold-eth/scaffold-eth-challenges#205]
### Description

Branch: `challenge-0-simple-nft`

⚔️ Side Quests > 🐟 Open Sea

The user interface on the Open Sea collections page has been updated. The instructions and screenshots in the side quest no longer correspond with what is shown on the Open Sea website.

### Steps to Reproduce

1. Navigate to the opensea collections screen as instructed in the side quest
2. Click the vertical ellipsis
3. Validate that the "Import an existing smart contract" option is no longer available

### Resolution

The side quest instructions and screenshots to create a collection for an existing smart contract on Open Sea should be updated to correspond with the new user interface.

**Comment by ZakGriffith** [comment]
Thank you for finding this.  The instructions in the Javascript and Typescript challenges have been updated to show that you no longer have to import and existing contract to OpenSea.
