### ISSUE TITLE
Error HH100: Network georli doesn't exist

### ISSUE THREAD

**Issue by andy3520** [scaffold-eth/scaffold-eth-challenges#262]
On the `Checkpoint 3: 💾 Deploy it! 🛰`  of `🚩 Challenge 0: 🎟 Simple NFT Example` - TYPESCRIPT

When I'm running the command `yarn run generate` it throw error:
```
Error HH100: Network georli doesn't exist
```

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/38342390/194704580-64b5f815-e15a-478a-88d4-1fa0ec5be364.png">

**Comment by ZakGriffith** [comment]
The network spelling is goerli instead of georli.  Might be misspelled in your hardhat config file.
