### ISSUE TITLE
Unhandled error after minting 9 NFTs.  Challenge 0.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/scaffold-eth-challenges#30]
When minting NFTs in Challenge 0, the frontend throws an error when attempting to mint any more than 8 NFTs.  Error:  ×
Unhandled Rejection (HTTPError): Too Many Requests.

**Comment by codenamejason** [comment]
we only have json data for those 8 nfts for demo purposes.

**Comment by codenamejason** [comment]
@ZakGriffith we could let them create new json files to mint what they want 🧐
