### ISSUE TITLE
Error HH604: Error running JSON-RPC server: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by ArnaudBand** [scaffold-eth/scaffold-eth-challenges#301]
I get this error after run `yarn chain` and when i run `yarn start`
- I got this error: 
``` Unhandled Rejection (Error): missing response (requestBody="{\"method\":\"eth_accounts\",\"params\":[],\"id\":42,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={}, url="http://localhost:8545", code=SERVER_ERROR, version=web/5.4.0)
Logger.makeError
/home/arnaud/challenge-1-decentralized-staking/packages/src.ts/index.ts:213
Logger.throwError
/home/arnaud/challenge-1-decentralized-staking/packages/src.ts/index.ts:225
(anonymous function)
/home/arnaud/challenge-1-decentralized-staking/packages/src.ts/index.ts:234
rejected
http://localhost:3000/static/js/0.chunk.js:94577:32
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.```

**Comment by shivamsk** [comment]
@ArnaudBand 
Got the same issue with node 18
Modified the "chain" in "scripts" of packages/hardhat/package.json to this. 

`"chain": "export SET NODE_OPTIONS=--openssl-legacy-provider && hardhat node --network hardhat --no-deploy" 
`
This should resolve it.

**Comment by route-2** [comment]
nvm install 16
nvm use 16 
should work!

**Comment by ArnaudBand** [comment]
> "chain": "export SET NODE_OPTIONS=--openssl-legacy-provider && hardhat node --network hardhat --no-deploy"



> @ArnaudBand Got the same issue with node 18 Modified the "chain" in "scripts" of packages/hardhat/package.json to this.
> 
> `"chain": "export SET NODE_OPTIONS=--openssl-legacy-provider && hardhat node --network hardhat --no-deploy" ` This should resolve it.

Thank you @shivamsk for your response. 
It helps me to solve that error.
