### ISSUE TITLE
add metamask opsional for better experience

### ISSUE THREAD

**Issue by haidarabdillah** [scaffold-eth/scaffold-eth-challenges#314]
people usually use metasask for transaction, so better to add network on your metamask, you can use this config to connect with metamask

![image](https://github.com/scaffold-eth/scaffold-eth-challenges/assets/113880800/2992a1e2-3449-43be-86e1-9768ad6f8d49)

**Comment by ZakGriffith** [comment]
We recommend using a burner wallet for the challenges until the contract is deployed to a testnet.
