### ISSUE TITLE
Yarn installation error

### ISSUE THREAD

**Issue by CodeWithUmair** [scaffold-eth/scaffold-eth-challenges#316]
I got an issue, When I clone 'challenge-1-decentralized-staking' I got yarn error see:

![image](https://github.com/scaffold-eth/scaffold-eth-challenges/assets/91899494/a2972dea-c161-4c2c-9101-3b8740d84d95)

**Comment by ZakGriffith** [comment]
Not sure what is causing this.  Hit us up in the Telegram for the specific challenge if you're still stuck.  The links can be found on each challenge at speedrunethereum.com
