### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'stake')

### ISSUE THREAD

**Issue by saqib772** [scaffold-eth/scaffold-eth-challenges#318]
TypeError: Cannot read properties of undefined (reading 'stake')
onClick
E:/blockchain/staking/challenge-1-decentralized-staking/packages/react-app/src/App.jsx:560
  557 | <Button
  558 |   type={balanceStaked ? "success" : "primary"}
  559 |   onClick={() => {
> 560 |     tx(writeContracts.Staker.stake({ value: ethers.utils.parseEther("0.5") }));
      | ^  561 |   }}
  562 | >
  563 |   🥩 Stake 0.5 ether!
View compiled
▶ 20 stack frames were collapsed.

**Comment by ZakGriffith** [comment]
Check the names of your Stake function compared to what the front end is calling.  I would bet is the capital S causing an issue.  Hit us up in the Challenge 1 Telegram if you're having issues.  https://speedrunethereum.com/challenge/decentralized-staking

**Comment by saqib772** [comment]
Ok I will Do it.
