### ISSUE TITLE
Challenge 0 issue: hardhat.config.js instructions not correct

### ISSUE THREAD

**Issue by OrlundoHubbard** [scaffold-eth/scaffold-eth-challenges#35]
In "Checkpoint 3: Deploy it!",   the hardhat.config.js file instruction does not show the correct explanation for changing to a different network. When changing the network to rinkeby, the correct code should read `const defaultNetwork = 'rinkeby';`

The image below shows what the current instructions on the site show -  `const defaultNetwork = 'NETWORKS.rinkeby';` which leads to an error in the console.

<img width="606" alt="Screen Shot 2021-12-18 at 9 59 23 PM" src="https://user-images.githubusercontent.com/88997637/146663411-9c8159ff-7507-47e7-9de5-b21c1778a0a2.png">

**Comment by ZakGriffith** [comment]
Good catch.  Screenshot and text have been updated.
