### ISSUE TITLE
bug: deposit logic: incorrect check for the need for approval

### ISSUE THREAD

**Issue by dvinubius** [scaffold-eth/scaffold-eth-challenges#40]
Approval is needed if expected token amount exceeds allowance.

The current logic doesn't take into account the expected token amount. Instead it compares allowance to the ethValuePlusExtra:

![Screenshot 2022-01-05 at 23 46 00](https://user-images.githubusercontent.com/32189942/148294217-842f9128-011a-499f-a7c9-ab627790f7a7.png)
)

The expected token amount is 
`(ethValue.mul(dexTokenBalance).div(dexEthBalance)).add(1)`, 
according to the smart contract logic:

![Screenshot 2022-01-05 at 23 57 19](https://user-images.githubusercontent.com/32189942/148295439-8ac8b72d-a878-4cb9-8e19-7634a59b7e0e.png)

So we don't need ethValuePlusExtra at all, instead we should check for smth like

`dexApproval.gte(expectedTokenAmount)`

**Comment by codenamejason** [comment]
this is actually pretty old and could use updating.. would you be interested in submitting a PR for this? @dvinubius

**Comment by dvinubius** [comment]
sure, will do
