### ISSUE TITLE
Challenge-5 Dex: 'props.hoistScanner is not a function' error

### ISSUE THREAD

**Issue by samlaf** [scaffold-eth/scaffold-eth-challenges#59]
There is an error in Challenge 5.
First of all, there was a path mistake for `useLookupAddress` import in `AddressInput.jsx`, which I believe to have fixed in https://github.com/scaffold-eth/scaffold-eth-challenges/pull/58#issue-1107342830

But even after this fix, clicking on either of the two wallets in the frontend results in:
![image](https://user-images.githubusercontent.com/9342524/150020856-30f4de26-90c1-4e89-bf9d-7eb5eeb995c4.png)

**Comment by samlaf** [comment]
Hi @codenamejason,
question: why was this assigned to me? I raised the bug because I don't know how to solve it.

**Comment by codenamejason** [comment]
Ha ha my bad

**Comment by ShivaShanmuganathan** [comment]
https://user-images.githubusercontent.com/30176438/153541815-847f6475-8665-463b-9e58-4e042c3062e6.mp4

Can we reopen this issue? 
I don't think this issue is resolved.
