### ISSUE TITLE
Challenge-0 - can't deploy with node 17

### ISSUE THREAD

**Issue by t3h2mas** [scaffold-eth/scaffold-eth-challenges#71]
`yarn deploy` fails on node 17.4.0. 

Here is the upstream issue https://github.com/nomiclabs/hardhat/issues/2239

Maybe it's worth adding a warning?

**Comment by adnfx2** [comment]
This has happened to me too, and the weirdest thing is that it gets fixed randomly after trying several times D:

**Comment by aarunjith** [comment]
happened to me as well. My node version is 17.5. Any solutions yet?

**Comment by metaverde** [comment]
Why don't you use node 16?
Isn't it standard practice to use even versions?
It seems like the simplest solution.

**Comment by t3h2mas** [comment]
@metaverde I did :) If this is the solution until hardhat figures out their solution, perhaps it should be documented
