### ISSUE TITLE
Challenge 0: 'cp' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by chrontast** [scaffold-eth/scaffold-eth-challenges#75]
When trying yarn surge windows users will get this error.

Easy fix is for them to remove cp from the surge script in package.json under react-app.

"surge": "cp build/index.html build/200.html && surge ./build"

**Comment by ZakGriffith** [comment]
We've added some extra instructions for Windows users in the instructions to remove the cp command.  That line needs to stay as is for other dev environments.
