### ISSUE TITLE
Build Challenge-0 (Simple-NFT)

### ISSUE THREAD

**Issue by codenamejason** [scaffold-eth/scaffold-eth-challenges#8]
Challenge-0-simple-nft needs to be built out.

**Comment by codenamejason** [comment]
I think Austin finished this one, just go through it and check for error.

**Comment by ZakGriffith** [comment]
I just ran through it a couple times as well and it's clean.  Looks good to close.

**Comment by codenamejason** [comment]
This has been completed.
